models:
  - name: locations
    columns:
      - name: location_id
        tests:
          - unique
      - name: borough
        tests:
          - not_null
      - name: zone
        tests:
          - not_null
      - name: service_zone
        tests:
          - not_null

  - name: trips
    columns:
      - name: pickup_datetime
        tests:
          - not_null
      - name: dropoff_datetime
        tests:
          - not_null
      - name: total_amount
        tests:
          - not_null
    tests:
      - dbt_utils.expression_is_true:
          expression: "trip_duration_minutes > 0"
      - dbt_utils.expression_is_true:
          expression: "passenger_count BETWEEN 1 AND 6"
      - dbt_utils.expression_is_true:
          expression: "dropoff_datetime > pickup_datetime"