dbt_transform:
  outputs:
    dev:
      dbname: final
      host: host.docker.internal
      pass: airflow
      port: 8432
      schema: dbt
      threads: 1
      type: postgres
      user: airflow
  target: dev