
models:
  - name: fact_crimes
    columns:
      - name: crime_id
        tests:
          - unique
          - not_null
      - name: crime_date
        tests:
          - not_null
      - name: location_key
        tests:
          - not_null
          - relationships:
                to: ref('dim_location')
                field: location_key
      - name: iucr_code
        tests:
          - not_null
          - relationships:
                to: ref('dim_crime_type')
                field: iucr_code
  
  - name: fact_arrests
    columns:
      - name: arrest_id
        tests:
          - unique
          - not_null
      - name: arrest_date
        tests:
          - not_null
      - name: charge_one_type
        tests:
          - accepted_values:
                values: ['felony', 'misdemeanor', 'other']
      - name: iucr_code
        tests:
          - relationships:
                to: ref('dim_crime_type')
                field: iucr_code